from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML, CSS
import os
from datetime import datetime

class PDFComposer:
    @staticmethod
    def build_report(profile_name, report_data, output_dir):
        # PLANTILLA CORPORATIVA V6 (Dinamica)
        html_template = """
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                @page {
                    size: A4; margin: 20mm; margin-top: 30mm; background-color: white;
                    @top-right { content: "Página " counter(page); font-family: Arial; font-size: 9pt; color: #7f8c8d; }
                }
                body { font-family: 'Helvetica', sans-serif; color: #2c3e50; margin: 0; line-height: 1.5; }
                .header-cnt { position: absolute; top: -15mm; left: 0; right: 0; border-bottom: 2px solid #e74c3c; padding-bottom: 10px; display: flex; justify-content: space-between; align-items: flex-end; }
                .logo-box { font-family: sans-serif; font-weight: bold; font-size: 24pt; letter-spacing: -1px; }
                .part-sen { color: #000000; } .part-net { color: #95a5a6; } 
                .section { page-break-before: always; }
                .section:first-of-type { page-break-before: auto; }
                .section-title { margin-top: 20px; margin-bottom: 15px; padding-left: 10px; border-left: 4px solid #e74c3c; color: #2c3e50; font-size: 16pt; font-weight: 700; }
                .card { background: #fdfdfd; border: 1px solid #bdc3c7; border-radius: 6px; padding: 15px; margin-bottom: 20px; break-inside: avoid; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
                .card-header { border-bottom: 1px solid #ecf0f1; padding-bottom: 8px; margin-bottom: 12px; font-weight: bold; font-size: 12pt; color: #34495e; }
                .kpi-row { display: flex; gap: 20px; margin-bottom: 15px; }
                .kpi-item { flex: 1; background: #ecf0f1; padding: 10px; border-radius: 4px; text-align: center; }
                .kpi-val { font-size: 16pt; font-weight: bold; color: #2980b9; }
                .kpi-lbl { font-size: 8pt; color: #7f8c8d; text-transform: uppercase; margin-top: 4px; }
                .chart-container { text-align: center; margin-top: 10px; }
                img { max-width: 100%; border: 1px solid #ecf0f1; border-radius: 4px; }
                .footer { position: fixed; bottom: 0; left: 0; right: 0; border-top: 1px solid #ecf0f1; padding-top: 5px; font-size: 8pt; color: #95a5a6; text-align: center; }
            </style>
        </head>
        <body>
            <div class="header-cnt">
                <div class="logo-box"><span class="part-sen">Sen</span><span class="part-net">Net</span><span style="font-size:14pt; color:#e74c3c;"> Energy BI</span></div>
                <div style="font-size: 10pt; color: #7f8c8d; text-align: right;">CLIENTE: {{ client }}<br>FECHA: {{ date }}</div>
            </div>

            {% for section_title, devices in data.items() %}
                <div class="section">
                <div class="section-title">{{ section_title }}</div>
                {% if not devices %}
                <div class="card">
                    <div class="card-header">Sin datos para este periodo</div>
                </div>
                {% endif %}
                {% for alias, kpi in devices.items() %}
                <div class="card">
                    <div class="card-header">{{ alias }}</div>
                    {% if kpi.get('main_value') %}
                    <div class="kpi-row">
                        <div class="kpi-item">
                            <div class="kpi-val" style="color:#2c3e50">{{ kpi.main_value }}</div>
                            <!-- ETIQUETA DINAMICA 1 -->
                            <div class="kpi-lbl">{{ kpi.get('label_main', 'Valor Principal') }}</div>
                        </div>
                        <div class="kpi-item">
                            <div class="kpi-val" style="color:#e74c3c">{{ kpi.secondary_value if kpi.secondary_value else '-' }}</div>
                             <!-- ETIQUETA DINAMICA 2 -->
                            <div class="kpi-lbl">{{ kpi.get('label_sec', 'Información Secundaria') }}</div>
                        </div>
                    </div>
                    {% endif %}
                    
                    {% if kpi.get('chart_img_1') %}
                    <div class="chart-container"><img src="data:image/png;base64,{{ kpi.chart_img_1 }}" /></div>
                    {% endif %}
                    {% if kpi.get('chart_img_2') %}
                    <div class="chart-container" style="margin-top:10px"><img src="data:image/png;base64,{{ kpi.chart_img_2 }}" /></div>
                    {% endif %}
                </div>
                {% endfor %}
                </div>
            {% endfor %}

            <div class="footer">SenNet IoT Solutions - Confidential Report - generated by AI Agent</div>
        </body>
        </html>
        """
        env = Environment(loader=FileSystemLoader('.'))
        render = env.from_string(html_template).render(client=profile_name.upper(), data=report_data, date=datetime.now().strftime("%d/%m/%Y %H:%M"))

        filename = f"Report_{profile_name}_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
        if not os.path.exists(output_dir): os.makedirs(output_dir)
        output_path = os.path.join(output_dir, filename)
        HTML(string=render).write_pdf(output_path)
        return output_path
